#pragma once
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <Windows.h>
#include <iostream>
#include <cmath>
#include <vector>
#include <cstddef>
#include <sstream>
#include <cstdint>
#include <thread>
